#!/bin/sh /etc/rc.common

USE_PROCD=1 # Enable procd for service management
START=99

# Define the path to the dfscheck.sh script
DFSCHECK_SCRIPT="/root/dfscheck.sh"

# Define default values for channel, fallback_channel, and backoff_type
DEFAULT_CHANNEL=108
DEFAULT_FALLBACK_CHANNELS="149 153" # 使用字符串而非数组

start_service() {
    logger -t "DFS-checker" "Starting with main channel: $DEFAULT_CHANNEL and fallbacks: $DEFAULT_FALLBACK_CHANNELS"
    procd_open_instance
    procd_set_param command "$DFSCHECK_SCRIPT" \
        "$DEFAULT_CHANNEL" $DEFAULT_FALLBACK_CHANNELS "${BACKOFF_TYPE:-fixed}"
    procd_set_param stdout 0 # Do not redirect stdout to log, this avoids "ok" status messages from flooding the log
    procd_set_param stderr 1 # Redirect stderr to log
    procd_set_param respawn  # Automatically restart the service if it crashes
    procd_close_instance
}

stop_service() {
    logger -t "DFS-checker" "Stopping dfscheck.sh"
    killall dfscheck.sh 2>/dev/null
}

restart() {
    stop
    start
}

status_service() {
    local pid=$(pidof dfscheck.sh)
    if [ -n "$pid" ]; then
        echo "dfscheck.sh is running with PID $pid."
        return 0
    else
        echo "dfscheck.sh is not running."
        return 1
    fi
}
